// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.springsource.petclinic.domain;

import com.springsource.petclinic.domain.OwnerDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect OwnerIntegrationTest_Roo_IntegrationTest {
    
    declare @type: OwnerIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: OwnerIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: OwnerIntegrationTest: @Transactional;
    
    @Autowired
    private OwnerDataOnDemand OwnerIntegrationTest.dod;
    
    @Test
    public void OwnerIntegrationTest.testCountOwners() {
        org.junit.Assert.assertNotNull("Data on demand for 'Owner' failed to initialize correctly", dod.getRandomOwner());
        long count = com.springsource.petclinic.domain.Owner.countOwners();
        org.junit.Assert.assertTrue("Counter for 'Owner' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void OwnerIntegrationTest.testFindOwner() {
        com.springsource.petclinic.domain.Owner obj = dod.getRandomOwner();
        org.junit.Assert.assertNotNull("Data on demand for 'Owner' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Owner' failed to provide an identifier", id);
        obj = com.springsource.petclinic.domain.Owner.findOwner(id);
        org.junit.Assert.assertNotNull("Find method for 'Owner' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Owner' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void OwnerIntegrationTest.testFindAllOwners() {
        org.junit.Assert.assertNotNull("Data on demand for 'Owner' failed to initialize correctly", dod.getRandomOwner());
        long count = com.springsource.petclinic.domain.Owner.countOwners();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Owner', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<com.springsource.petclinic.domain.Owner> result = com.springsource.petclinic.domain.Owner.findAllOwners();
        org.junit.Assert.assertNotNull("Find all method for 'Owner' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Owner' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void OwnerIntegrationTest.testFindOwnerEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Owner' failed to initialize correctly", dod.getRandomOwner());
        long count = com.springsource.petclinic.domain.Owner.countOwners();
        if (count > 20) count = 20;
        java.util.List<com.springsource.petclinic.domain.Owner> result = com.springsource.petclinic.domain.Owner.findOwnerEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Owner' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Owner' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void OwnerIntegrationTest.testFlush() {
        com.springsource.petclinic.domain.Owner obj = dod.getRandomOwner();
        org.junit.Assert.assertNotNull("Data on demand for 'Owner' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Owner' failed to provide an identifier", id);
        obj = com.springsource.petclinic.domain.Owner.findOwner(id);
        org.junit.Assert.assertNotNull("Find method for 'Owner' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyOwner(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Owner' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void OwnerIntegrationTest.testMerge() {
        com.springsource.petclinic.domain.Owner obj = dod.getRandomOwner();
        org.junit.Assert.assertNotNull("Data on demand for 'Owner' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Owner' failed to provide an identifier", id);
        obj = com.springsource.petclinic.domain.Owner.findOwner(id);
        boolean modified =  dod.modifyOwner(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        com.springsource.petclinic.domain.Owner merged = (com.springsource.petclinic.domain.Owner) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Owner' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void OwnerIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Owner' failed to initialize correctly", dod.getRandomOwner());
        com.springsource.petclinic.domain.Owner obj = dod.getNewTransientOwner(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Owner' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Owner' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Owner' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void OwnerIntegrationTest.testRemove() {
        com.springsource.petclinic.domain.Owner obj = dod.getRandomOwner();
        org.junit.Assert.assertNotNull("Data on demand for 'Owner' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Owner' failed to provide an identifier", id);
        obj = com.springsource.petclinic.domain.Owner.findOwner(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Owner' with identifier '" + id + "'", com.springsource.petclinic.domain.Owner.findOwner(id));
    }
    
}
