// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.springsource.petclinic.domain;

import com.springsource.petclinic.domain.Owner;
import com.springsource.petclinic.domain.OwnerDataOnDemand;
import com.springsource.petclinic.domain.OwnerIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect OwnerIntegrationTest_Roo_IntegrationTest {
    
    declare @type: OwnerIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: OwnerIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: OwnerIntegrationTest: @Transactional;
    
    @Autowired
    OwnerDataOnDemand OwnerIntegrationTest.dod;
    
    @Test
    public void OwnerIntegrationTest.testCountOwners() {
        Assert.assertNotNull("Data on demand for 'Owner' failed to initialize correctly", dod.getRandomOwner());
        long count = Owner.countOwners();
        Assert.assertTrue("Counter for 'Owner' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void OwnerIntegrationTest.testFindOwner() {
        Owner obj = dod.getRandomOwner();
        Assert.assertNotNull("Data on demand for 'Owner' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Owner' failed to provide an identifier", id);
        obj = Owner.findOwner(id);
        Assert.assertNotNull("Find method for 'Owner' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Owner' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void OwnerIntegrationTest.testFindAllOwners() {
        Assert.assertNotNull("Data on demand for 'Owner' failed to initialize correctly", dod.getRandomOwner());
        long count = Owner.countOwners();
        Assert.assertTrue("Too expensive to perform a find all test for 'Owner', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Owner> result = Owner.findAllOwners();
        Assert.assertNotNull("Find all method for 'Owner' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Owner' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void OwnerIntegrationTest.testFindOwnerEntries() {
        Assert.assertNotNull("Data on demand for 'Owner' failed to initialize correctly", dod.getRandomOwner());
        long count = Owner.countOwners();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Owner> result = Owner.findOwnerEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Owner' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Owner' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void OwnerIntegrationTest.testFlush() {
        Owner obj = dod.getRandomOwner();
        Assert.assertNotNull("Data on demand for 'Owner' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Owner' failed to provide an identifier", id);
        obj = Owner.findOwner(id);
        Assert.assertNotNull("Find method for 'Owner' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyOwner(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Owner' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void OwnerIntegrationTest.testMergeUpdate() {
        Owner obj = dod.getRandomOwner();
        Assert.assertNotNull("Data on demand for 'Owner' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Owner' failed to provide an identifier", id);
        obj = Owner.findOwner(id);
        boolean modified =  dod.modifyOwner(obj);
        Integer currentVersion = obj.getVersion();
        Owner merged = (Owner)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Owner' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void OwnerIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Owner' failed to initialize correctly", dod.getRandomOwner());
        Owner obj = dod.getNewTransientOwner(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Owner' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Owner' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Owner' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void OwnerIntegrationTest.testRemove() {
        Owner obj = dod.getRandomOwner();
        Assert.assertNotNull("Data on demand for 'Owner' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Owner' failed to provide an identifier", id);
        obj = Owner.findOwner(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Owner' with identifier '" + id + "'", Owner.findOwner(id));
    }
    
}
