// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.springsource.petclinic.domain;

import com.springsource.petclinic.domain.PetDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PetIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PetIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PetIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: PetIntegrationTest: @Transactional;
    
    @Autowired
    private PetDataOnDemand PetIntegrationTest.dod;
    
    @Test
    public void PetIntegrationTest.testCountPets() {
        org.junit.Assert.assertNotNull("Data on demand for 'Pet' failed to initialize correctly", dod.getRandomPet());
        long count = com.springsource.petclinic.domain.Pet.countPets();
        org.junit.Assert.assertTrue("Counter for 'Pet' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PetIntegrationTest.testFindPet() {
        com.springsource.petclinic.domain.Pet obj = dod.getRandomPet();
        org.junit.Assert.assertNotNull("Data on demand for 'Pet' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Pet' failed to provide an identifier", id);
        obj = com.springsource.petclinic.domain.Pet.findPet(id);
        org.junit.Assert.assertNotNull("Find method for 'Pet' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Pet' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void PetIntegrationTest.testFindAllPets() {
        org.junit.Assert.assertNotNull("Data on demand for 'Pet' failed to initialize correctly", dod.getRandomPet());
        long count = com.springsource.petclinic.domain.Pet.countPets();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Pet', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<com.springsource.petclinic.domain.Pet> result = com.springsource.petclinic.domain.Pet.findAllPets();
        org.junit.Assert.assertNotNull("Find all method for 'Pet' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Pet' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PetIntegrationTest.testFindPetEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Pet' failed to initialize correctly", dod.getRandomPet());
        long count = com.springsource.petclinic.domain.Pet.countPets();
        if (count > 20) count = 20;
        java.util.List<com.springsource.petclinic.domain.Pet> result = com.springsource.petclinic.domain.Pet.findPetEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Pet' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Pet' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PetIntegrationTest.testFlush() {
        com.springsource.petclinic.domain.Pet obj = dod.getRandomPet();
        org.junit.Assert.assertNotNull("Data on demand for 'Pet' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Pet' failed to provide an identifier", id);
        obj = com.springsource.petclinic.domain.Pet.findPet(id);
        org.junit.Assert.assertNotNull("Find method for 'Pet' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyPet(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Pet' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PetIntegrationTest.testMerge() {
        com.springsource.petclinic.domain.Pet obj = dod.getRandomPet();
        org.junit.Assert.assertNotNull("Data on demand for 'Pet' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Pet' failed to provide an identifier", id);
        obj = com.springsource.petclinic.domain.Pet.findPet(id);
        boolean modified =  dod.modifyPet(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        com.springsource.petclinic.domain.Pet merged =  obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Pet' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PetIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Pet' failed to initialize correctly", dod.getRandomPet());
        com.springsource.petclinic.domain.Pet obj = dod.getNewTransientPet(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Pet' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Pet' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Pet' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void PetIntegrationTest.testRemove() {
        com.springsource.petclinic.domain.Pet obj = dod.getRandomPet();
        org.junit.Assert.assertNotNull("Data on demand for 'Pet' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Pet' failed to provide an identifier", id);
        obj = com.springsource.petclinic.domain.Pet.findPet(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Pet' with identifier '" + id + "'", com.springsource.petclinic.domain.Pet.findPet(id));
    }
    
}
