// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.springsource.petclinic.domain;

import com.springsource.petclinic.domain.VetIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect VetIntegrationTest_Roo_Configurable {
    
    declare @type: VetIntegrationTest: @Configurable;
    
}
