// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.springsource.petclinic.domain;

import com.springsource.petclinic.domain.Pet;
import com.springsource.petclinic.domain.PetDataOnDemand;
import com.springsource.petclinic.domain.Vet;
import com.springsource.petclinic.domain.VetDataOnDemand;
import com.springsource.petclinic.domain.Visit;
import java.lang.String;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect VisitDataOnDemand_Roo_DataOnDemand {
    
    declare @type: VisitDataOnDemand: @Component;
    
    private Random VisitDataOnDemand.rnd = new SecureRandom();
    
    private List<Visit> VisitDataOnDemand.data;
    
    @Autowired
    private PetDataOnDemand VisitDataOnDemand.petDataOnDemand;
    
    @Autowired
    private VetDataOnDemand VisitDataOnDemand.vetDataOnDemand;
    
    public Visit VisitDataOnDemand.getNewTransientVisit(int index) {
        Visit obj = new Visit();
        setDescription(obj, index);
        setPet(obj, index);
        setVet(obj, index);
        setVisitDate(obj, index);
        return obj;
    }
    
    public void VisitDataOnDemand.setDescription(Visit obj, int index) {
        String description = "description_" + index;
        if (description.length() > 255) {
            description = description.substring(0, 255);
        }
        obj.setDescription(description);
    }
    
    public void VisitDataOnDemand.setPet(Visit obj, int index) {
        Pet pet = petDataOnDemand.getRandomPet();
        obj.setPet(pet);
    }
    
    public void VisitDataOnDemand.setVet(Visit obj, int index) {
        Vet vet = vetDataOnDemand.getRandomVet();
        obj.setVet(vet);
    }
    
    public void VisitDataOnDemand.setVisitDate(Visit obj, int index) {
        Date visitDate = new Date(new Date().getTime() - 10000000L);
        obj.setVisitDate(visitDate);
    }
    
    public Visit VisitDataOnDemand.getSpecificVisit(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Visit obj = data.get(index);
        return Visit.findVisit(obj.getId());
    }
    
    public Visit VisitDataOnDemand.getRandomVisit() {
        init();
        Visit obj = data.get(rnd.nextInt(data.size()));
        return Visit.findVisit(obj.getId());
    }
    
    public boolean VisitDataOnDemand.modifyVisit(Visit obj) {
        return false;
    }
    
    public void VisitDataOnDemand.init() {
        data = Visit.findVisitEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Visit' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<com.springsource.petclinic.domain.Visit>();
        for (int i = 0; i < 10; i++) {
            Visit obj = getNewTransientVisit(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> it = e.getConstraintViolations().iterator(); it.hasNext();) {
                    ConstraintViolation<?> cv = it.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
