// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.springsource.petclinic.domain;

import com.springsource.petclinic.domain.Owner;
import javax.persistence.Entity;

privileged aspect Owner_Roo_Jpa_Entity {
    
    declare @type: Owner: @Entity;
    
}
